export const SHIKI_OPTS = {
  langAlias: {
    cfg: 'ini',
    cl: 'cpp',
    filters: 'xml',
    gradle: 'groovy',
    h: 'objective-cpp',
    hpp: 'objective-cpp',
    map: 'json',
    m: 'objective-c',
    mm: 'objective-cpp',
    plist: 'xml',
    podspec: 'ruby',
    pom: 'xml',
    pro: 'properties',
    props: 'xml',
    sln: 'ini',
    vcxproj: 'xml',
    tsbuildinfo: 'json',
    xcprivacy: 'xml',
    xcworkspacedata: 'xml',
  },
} as const;
