import { cancel, confirm, isCancel, log, spinner } from '@clack/prompts';
import { $ } from 'bun';
import { yellow } from 'picocolors';

import { type LibraryDataEntryType } from '../../types.ts';
import { deleteFile } from '../../utils.ts';

import { BASE_REPO, LIBRARIES_FILE, OXFMT_TMP_CONFIG } from './constants';

export async function forkRNDRepo() {
  const progress = spinner();
  progress.start('Forking repository');

  const forkCreationResult = await $`gh repo fork ${BASE_REPO} --clone=false --default-branch-only`.quiet();

  let forkRepo;

  if (forkCreationResult.stderr.toString().length > 0) {
    forkRepo =
      forkCreationResult.stderr.toString().match(/([^/\s]+\/[^/\s]+)(?=\s+already exists\b)/)?.[1] ?? undefined;
    log.warn(`${forkRepo} already exists`);
  } else if (forkCreationResult.stdout.toString().length > 0) {
    forkRepo = forkCreationResult.stdout.toString().match(/(?<=Created fork\s)([^/\s]+\/[^/\s]+)/)?.[1] ?? undefined;
  }

  if (!forkRepo) {
    cancel(`Cannot extract fork name from the GitHub CLI command output`);
    process.exit(1);
  }

  progress.stop('Repository has been forked');

  return forkRepo;
}

export async function createBranchInFork(forkRepo: string, branchName: string) {
  const progress = spinner();
  progress.start('Creating branch in the fork');

  const forkSHA = (await $`gh api repos/${forkRepo}/git/ref/heads/main -q .object.sha`.text()).trim();

  try {
    await $`gh api repos/${forkRepo}/git/refs -f ref="refs/heads/${branchName}" -f sha="${forkSHA}"`.quiet();
  } catch (error) {
    if (error instanceof $.ShellError) {
      if (error.stderr.toString().includes('HTTP 422')) {
        log.warn(`Branch ${branchName} already exist in ${forkRepo}`);
      } else {
        cancel(`Branch creation failed with code ${error.exitCode}`);
        process.exit(1);
      }
    } else {
      cancel(error as string);
      process.exit(1);
    }
  }

  progress.stop('Branch created in the fork');
}

export async function fetchLibrariesFromForkBranch(forkRepo: string, branchName: string) {
  const librariesJsonContent =
    await $`gh api repos/${forkRepo}/contents/${LIBRARIES_FILE}?ref=${branchName} -q .content`.text();
  return JSON.parse(atob(librariesJsonContent)) as LibraryDataEntryType[];
}

export async function printSummaryAndConfirm(packageEntry: LibraryDataEntryType, showWarning = false) {
  log.info(`The following entry will be proposed in the PR:\n\n${JSON.stringify(packageEntry, null, 2)}`);

  if (showWarning) {
    log.warn(
      yellow(
        'Auto-submit functionality is experimental. You can always abort the process and submit new entry manually, if you see any issues with the autogenerated entry below.'
      )
    );
  }

  const continueProcess = await confirm({
    message: 'Would you like to continue the process?',
  });

  if (isCancel(continueProcess) || !continueProcess) {
    cancel('Submission cancelled.');
    process.exit(0);
  }
}

export async function createAndPushCommit(
  forkRepo: string,
  branchName: string,
  librariesArray: LibraryDataEntryType[],
  message: string
) {
  const librariesJsonSHA = (
    await $`gh api repos/${forkRepo}/contents/${LIBRARIES_FILE}?ref=${branchName} -q .sha`.text()
  ).trim();

  await Bun.write(LIBRARIES_FILE, JSON.stringify(librariesArray, null, 2));
  await Bun.write(OXFMT_TMP_CONFIG, JSON.stringify({}));

  await $`bunx --silent oxfmt@latest ${LIBRARIES_FILE} -c ${OXFMT_TMP_CONFIG}`;

  const tempLibrariesFile = Bun.file(LIBRARIES_FILE);

  await Bun.write(
    'commit.json',
    JSON.stringify({
      message,
      branch: branchName,
      sha: librariesJsonSHA,
      content: btoa(await tempLibrariesFile.text()),
    })
  );

  await $`gh api repos/${forkRepo}/contents/${LIBRARIES_FILE} -X PUT -H "Content-Type: application/json" --input commit.json"`.quiet();

  await tempLibrariesFile.delete();

  await deleteFile(OXFMT_TMP_CONFIG);
  await deleteFile('commit.json');
}

export async function createPRForRND(
  forkRepo: string,
  branchName: string,
  message: string,
  packageName: string,
  repositoryUrl: string
) {
  const progress = spinner();
  progress.start('Creating PR in React Native Directory repository');

  await Bun.write(
    'pr.md',
    `# 📝 Why & how

This PR adds \`${packageName}\` (${repositoryUrl}) package to the directory.

> [!NOTE]
> This is an automatic submission created via \`rn-directory\` CLI.

# ✅ Checklist

- [x] Added library to **\`react-native-libraries.json\`**
`
  );

  const creationResponse =
    await $`gh pr create -R ${BASE_REPO} --head ${forkRepo.split('/')[0]}:${branchName} --base main --title "${message}" --body-file pr.md`.quiet();

  log.info(creationResponse.stdout.toString());

  await deleteFile('pr.md');

  progress.stop('PR in React Native Directory has been created');
}
