name: "[CODE] Deploy preview website"

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  build:
    if: ${{ github.event.label.name == 'deploy' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: Deploy
        shell: bash
        run: bunx vercel --force --token "$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          # https://spectrum.chat/zeit/now/solved-project-linking-and-ci-cd-pipelines~5e6eb62a-9d56-47ac-9e32-0d973a523787
          VERCEL_ORG_ID: 'team_IsLEAhLb9cZj6y1Bud9XYmeK'
          VERCEL_PROJECT_ID: 'QmecQ8hTu4DUHv6js5U8L9pJ9vp54mg1bmRLWaS5RZCyt4'
