name: "[CODE] Deploy production website"

on:
  push:
    branches: [main]
    paths-ignore:
      - react-native-libraries.json
  schedule:
    # Run every 1 hour - https://crontab.guru/#0_*/1_*_*_*
    - cron: '0 */1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://reactnative.directory
    steps:
    - uses: actions/checkout@v4
    - name: Use Bun
      uses: oven-sh/setup-bun@v2
    - name: Deploy
      shell: bash
      run: bunx vercel --force --token "$VERCEL_TOKEN" --prod
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID: 'team_IsLEAhLb9cZj6y1Bud9XYmeK'
        VERCEL_PROJECT_ID: 'QmecQ8hTu4DUHv6js5U8L9pJ9vp54mg1bmRLWaS5RZCyt4'
        CONVEX_DEPLOYMENT: 'dev:calm-quail-572'
        NEXT_PUBLIC_CONVEX_URL: 'https://calm-quail-572.convex.cloud'
