name: "[DATA] Test and Validate"

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - react-native-libraries.json

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Bun
      uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      run: bun install
    - name: Validate react-native-libraries.json
      run: bun data:validate
    - name: Test react-native-libraries.json
      run: bun data:test
    - name: Check new entries in react-native-libraries.json
      run: bun ci:validate
      env:
        CI_CHECKS_TOKEN: ${{ github.token }}
